version: '3.8'
services:
  fll-sim:
    build: .
    container_name: fll-sim-cloud
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
